parameters:
#    tdev_contact.example.class: Tdev\ContactBundle\Example

services:
#    tdev_contact.example:
#        class: %tdev_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
