tdev_news_add:
    path:     /add
    defaults: { _controller: TdevNewsBundle:News:add }
tdev_news_view:
    path:     /view/{id}
    defaults: { _controller: TdevNewsBundle:News:view }
    requirements:
        id: \d+
tdev_news_edit:
    path:     /edit/{id}
    defaults: { _controller: TdevNewsBundle:News:edit }
    requirements:
        id: \d+
tdev_news_delete:
    path:     /delete/{id}
    defaults: { _controller: TdevNewsBundle:News:delete }
    requirements:
        id: \d+
tdev_news_homepage:
    path:     /{page}
    defaults: { _controller: TdevNewsBundle:News:index , page: 1}
    requirements:
        id: \d*