parameters:
#    tdev_news.example.class: Tdev\NewsBundle\Example

services:
#    tdev_news.example:
#        class: %tdev_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
